FROM python:3.11-alpine

WORKDIR /app

COPY app.py .

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY script.sql .

WORKDIR /app/template .

COPY templates/index.html .


ENTRYPOINT ["python3","app.py"]