FROM python:3.11-alpine

WORKDIR /app

COPY app.py .

COPY requirements.txt .

RUN apk add curl

COPY script.sql .

WORKDIR /app/template

COPY template/index.html .

RUN pip install -r /app/requirements.txt

WORKDIR /app

CMD [ "python", "./app.py" ]
